name: Build and release RSSpire

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      changelogSkipped: ${{ steps.changelog.outputs.skipped }}
      changelogTag: ${{ steps.changelog.outputs.tag }}
      changelogCleanLog: ${{ steps.changelog.outputs.clean_changelog }}
    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Conventional Changelog Action
      if: ${{ github.ref == 'refs/heads/main' }}
      id: changelog
      uses: TriPSs/conventional-changelog-action@v5.2.1
      with:
        github-token: ${{ secrets.github_token }}
        release-count: '50'

    - name: Markdown to HTML
      uses: BaileyJM02/markdown-to-pdf@v1
      with:
        input_path: CHANGELOG.md
        output_dir: app/src/main/assets/
        build_html: true
        build_pdf: false
        table_of_contents: false

    - name: Get default version name
      id: version
      run: echo "DEFAULT_VERSION_NAME=${{ github.ref_name }}" >> $GITHUB_OUTPUT

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.SIGNING_KEY }}
      run: |
        echo $ENCODED_STRING > keystore-b64.txt
        base64 -d keystore-b64.txt > app/keystore.jks

    - name: Build Release APK
      env:
        VERSION_NAME: ${{ steps.changelog.outputs.tag || steps.version.outputs.DEFAULT_VERSION_NAME }}
        VERSION_CODE: ${{ github.run_number }}
        SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_PATH }}
        SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      run: ./gradlew assembleRelease

    - name: Build Release BUNDLE
      env:
        VERSION_NAME: ${{ steps.changelog.outputs.tag || steps.version.outputs.DEFAULT_VERSION_NAME }}
        VERSION_CODE: ${{ github.run_number }}
        SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_PATH }}
        SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      run: ./gradlew bundleRelease

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-artifacts
        path: |
          app/build/outputs/apk/release/RSSpire_*.apk
          app/build/outputs/bundle/release/RSSpire_*.aab

  release:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.changelogSkipped == 'false' }}
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: release-artifacts

    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        draft: true
        tag: ${{ needs.build.outputs.changelogTag }}
        name: RSSpire ${{ needs.build.outputs.changelogTag }}
        body: ${{ needs.build.outputs.changelogCleanLog }}
        artifactErrorsFailBuild: true
        artifacts: apk/release/RSSpire_*.apk, bundle/release/RSSpire_*.aab